MonitOR/Controllers/DataController.cs
using MonitOR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace MonitOR.Controllers
{
    public class DataController : Controller
    {
        public static ModelServices modelServices = new ModelServices();

        // GET: Data
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DownloadRaw()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult SubmitData()
        {
            //http://localhost:50221/Data/SubmitData?or_id=1&sensor_id=1&open_time=2016-03-17T22:10:32.300&seconds=2000
            try
            {
                EventViewModel model = new EventViewModel();
                model.operatingRoomID = Int32.Parse(Request.Params["or_id"]);
                model.sensorID = Int32.Parse(Request.Params["sensor_id"]);
                //model.timeStamp = new DateTime(Int64.Parse(Request.Params["open_time"]));
                model.timeStamp = Convert.ToDateTime(Request.Params["open_time"]);
                model.duration = Int32.Parse(Request.Params["seconds"]);
                if (modelServices.AddOpenEvent(model))
                {
                    //Send back 204 Success without sending any data back
                    return new HttpStatusCodeResult(HttpStatusCode.NoContent);
                }
                else
                {
                    //Send back 500
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }
            }
            catch
            {
                //Send back 500
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [HttpGet]
        public ActionResult ViewData()
        {
            var model = new SensorDataViewModel(modelServices.getAllOperatingRooms());
            return View(model);
        }

        [HttpGet]
        public FileContentResult DownloadData()
        {
            int operatingRoomID = Int32.Parse(Request.Params["operatingRoomID"]);
            int sensorID = Int32.Parse(Request.Params["sensorID"]);
            string fromDate = Request.Params["fromDate"];
            string fromTime = Request.Params["fromTime"];
            string toDate = Request.Params["toDate"];
            string toTime = Request.Params["toTime"];
            DateTime start = Convert.ToDateTime(fromDate + " " + fromTime);
            DateTime end = Convert.ToDateTime(toDate + " " + toTime);
            List<OpenEvent> events = modelServices.getEventsBySensorWithTimeConstraints(operatingRoomID, sensorID, start, end);
            string result = "Operating_Room_ID, Sensor_ID, Time, Duration" + Environment.NewLine;
            for (int i = 0; i < events.Count; i++ )
            {
                result = result + modelServices.convertOpenEventToCsvString(events[i]) + Environment.NewLine;
            }
            return File(Encoding.UTF8.GetBytes(result), "text/csv", "Event Data.csv");
        }
    }
}

MonitOR/Views/Data/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

MonitOR/Views/Data/SubmitData.cshtml
@{
    ViewBag.Title = "SubmitData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SubmitData</h2>

MonitOR/Views/Data/ViewData.cshtml
@using MonitOR.Models
@model SensorDataViewModel
@using System.Web.Mvc

@{
    ViewBag.Title = "ViewData";
}

@using (Html.BeginForm("ViewData", "Data", FormMethod.Get, new { @id = "ViewDataForm" }))
{
    <div class="row" style="margin-top:20px;">
        <div class="col">
            <label>Operating Room</label>
            @Html.DropDownListFor(m => m.SelectedOperatingRoomID, @Model.OperatingRooms, "Select OR", new { @class = "browser-default" })
        </div>
        <div class="col">
            <label>Sensor</label>
            @Html.DropDownListFor(m => m.SelectedSensorID, @Model.Sensors, "Select Sensor", new { @class = "browser-default", @disabled = "disabled" })
        </div>
        <div class="col">
            <label>From</label>
            <div>
                <input type="date" class="datepicker" name="fromdate" style="width:120px;" placeholder="MM/DD/YYYY">
                <input type="time" name="fromtime" style="width:120px;">
            </div>
        </div>
        <div class="col">
            <label>To</label>
            <div>
                <input type="date" class="datepicker" name="todate" style="width:120px;" placeholder="MM/DD/YYYY">
                <input type="time" name="totime" style="width:120px;">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a id="btnSubmit" class="waves-effect waves-light btn green darken-3">Submit</a>
        </div>
    </div>

    <div id="failModal" class="modal" style="width: 40%">
        <div class="modal-content">
            <h4>Failure to Complete Action</h4>
            <p>You must fill out all values!</p>
        </div>
        <div class="modal-footer">
            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OK</a>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        var firstOption = $($("#SelectedOperatingRoomID").children()[0]);
        firstOption.attr("disabled", "disabled");
        $("#SelectedOperatingRoomID").material_select();

        var firstOption = $($("#SelectedSensorID").children()[0]);
        firstOption.attr("disabled", "disabled");
        $("#SelectedSensorID").material_select();

        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'mm/dd/yyyy',
        });

        $('#btnSubmit').click(function (e) {
            var orID = $('#SelectedOperatingRoomID').prop('selectedIndex');
            var sensorID = $('#SelectedSensorID').prop("selectedIndex");
            var fromDate = $("input[name=fromdate]").val();
            var fromTime = $("input[name=fromtime]").val();
            var toDate = $("input[name=todate]").val();
            var toTime = $("input[name=totime]").val();

            if (orID == 0 ||
                sensorID == 0 ||
                fromDate === "" ||
                fromTime === "" ||
                toDate === "" ||
                toTime === "")
            {
                $("#failModal").openModal();
                e.preventDefault();
                return false;
            }
            var url = encodeURI('/Data/DownloadData?operatingRoomID='+orID+'&sensorid='+sensorID+"&fromDate="+fromDate+"&fromTime="+fromTime+"&toDate="+toDate+"&toTime="+toTime)
            window.location = url;
            //$.ajax({
            //    url: encodeURI('/Data/DownloadData?operatingRoomID='+orID+'&sensorid='+sensorID+"&fromDate="+fromDate+"&fromTime="+),
            //    type: "GET"
            //});

            return true;
        });

        $("#SelectedOperatingRoomID").change(function () {
            var firstOption = $($(this).children()[0]);
            if (firstOption.prop("selected") === "true")
            {
                $("#SelectedSensorID").attr("disabled", "disabled");
            }
            else {
                var id = $(this).children()[$(this).prop("selectedIndex")].value;
                $.ajax({
                    url: "/Sensor/GetSensors?operatingRoomId=" + id,
                    dataType: "json"
                }).success(function (data) {
                    $("#SelectedSensorID").attr("disabled", null);
                    var model = $.parseJSON(data);
                    var sensors = model.Sensors;
                    $("#SelectedSensorID").find("option[value!='']").remove();
                    for (var index = 0; index < sensors.length; index++)
                    {
                        var option = $("<option/>", { value: sensors[index].Value });
                        option.text(sensors[index].Text);
                        $("#SelectedSensorID").append(option);
                    }
                }).error(function () {
                    $("#SelectedSensorID").attr("disabled", "disabled");
                });
            }
        });
    });


</script>